-- CREATE DATABASE PersonalBlogTest;

-- USE PersonalBlogTest;

DROP TABLE POST;
DROP TABLE USERS;


CREATE TABLE USERS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(500) NOT NULL
);


CREATE TABLE POST(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Title NVARCHAR(250) NULL,
    CreatedDate DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
    Content TEXT NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY FK_POST_USERS (UserID) REFERENCES USERS(ID)
);



INSERT INTO USERS VALUES (NULL, 'MANDY', '123');
INSERT INTO USERS VALUES (NULL, 'MANDY1339', 'mysecret');
INSERT INTO USERS VALUES (NULL, 'Benji', 'benjisecret');
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'MY CONTENT HERE COñO', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'MY CONTENT HERE COñOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO OOOO O OOOOOO O', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'ASDKLFASDF;LJ SAFKLDSA FJAS;KLD ALSKD ALKSDF LKASDF LKASJFLKASDFL KAJSFLKJ ASLKDJ ASLKF OIWQEUYTOPIWQH TASLNFG WLKATH OP8AWSG LKA;S JAK, VNM,XZC IOATH  ASNGFKAMSD FKJAASDF JLKASFMN ,FXXXXXX H H HSAHKDFKLSADFU8IUUIUUUUU U U UIASDFIOASJ LKASJ FL;KASJFLASDFJ ', 1);
INSERT INTO POST (Title, Content, UserID) VALUES ('TITLE1', 'BBBBBBBBBBBBBBBBBBBBBBB     AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBBBBBBBB DDDDDDDDDDDDD S ASD BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB', 1);

SELECT * FROM USERS;
SELECT * FROM POST;

